http:
  routers:
    bentopdf:
      rule: Host(`bentopdf.app.home.arpa`)
      entryPoints:
        - websecure
      tls:
        certResolver: stepca
      middlewares:
        - authelia@file
        - secure-headers@file
      service: bentopdf-svc

  services:
    bentopdf-svc:
      loadBalancer:
        servers:
          - url: http://bentopdf:8080
