http:
  routers:
    dozzle:
      rule: Host(`dozzle.app.home.arpa`)
      entryPoints:
        - websecure
      tls:
        certResolver: stepca
      middlewares:
        - authelia@file
        - secure-headers@file
      service: dozzle-svc

  services:
    dozzle-svc:
      loadBalancer:
        servers:
          - url: http://dozzle:8080