http:
  routers:
    pihole:
      rule: Host(`pihole.app.home.arpa`)
      entryPoints:
        - websecure
      tls:
        certResolver: stepca
      middlewares:
        - pihole-redirect
        - authelia@file
        - secure-headers
      service: pihole-svc

    traefik:
      rule: Host(`traefik.app.home.arpa`)
      entryPoints:
        - websecure
      tls:
        certResolver: stepca
      middlewares:
        - authelia@file
        - secure-headers
      service: api@internal

  middlewares:
    pihole-redirect:
      redirectRegex:
        regex: "^https?://pihole\\.app\\.home\\.arpa/?$"
        replacement: "https://pihole.app.home.arpa/admin/"
        permanent: true
    secure-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: false
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true

  services:
    pihole-svc:
      loadBalancer:
        servers:
          - url: http://pihole:80