http:
  routers:
    glances:
      rule: Host(`glances.app.home.arpa`)
      entryPoints:
        - websecure
      tls:
        certResolver: stepca
      middlewares:
        - authelia@file
        - secure-headers@file
      service: glances-svc

  services:
    glances-svc:
      loadBalancer:
        servers:
          - url: http://glances:61208
