http:
  routers:
    netdata:
      rule: Host(`netdata.app.home.arpa`)
      entryPoints:
        - websecure
      tls:
        certResolver: stepca
      middlewares:
        - authelia@file
        - secure-headers@file
      service: netdata-svc

  services:
    netdata-svc:
      loadBalancer:
        servers:
          - url: http://netdata:19999