http:
  routers:
    uptime-kuma:
      rule: Host(`uptime-kuma.app.home.arpa`)
      entryPoints:
        - websecure
      tls:
        certResolver: stepca
      middlewares:
        - authelia@file
        - secure-headers@file
      service: uptime-kuma-svc

  services:
    uptime-kuma-svc:
      loadBalancer:
        servers:
          - url: http://uptime-kuma:3001
